spring:
  application:
    name: lingxi
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 静态资源
  resources:
    static-locations: classpath:web/
  profiles:
    active: '@profilesActive@'

mybatis:
  type-aliases-package: me.happycao.lingxi.model
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    root: info
  path: log
  config: classpath:logback-spring.xml

# 此地址由nginx代理，即前端访问http://localhost/rss/ 指向 rss-path
rss-path:
  windowsPath: D:/data/rss
  linuxPath: /data/html/rss

# 由nginx代理了实际地址，详情搜索资源采集，仅供学习
inc-cnf:
  apiUrl: http://localhost/inc/api